name: 'bump-version-action'
description: 'Conventional commits compliant version manager.'
branding:
  icon: tag
  color: blue

inputs:
  version-tag-prefix:
    description: 'version tag prefix. Default: v'
    default: 'v'
    required: false
  commit-user-name:
    description: 'The user name used to create the version update commit'
    required: false
  commit-user-email:
    description: 'The user email used to create the version update commit'
    required: false
  commit-message:
    description: 'The message of the version update commit. (see message fields for reference)'
    required: false
    default: |
      release: new version {version} [skip ci]

      {changelog}
  commit-add:
    description: 'Additional files to add to the version update commit'
    required: false
    default: ''

outputs:
  version:
    description: 'The calculated new version'
  current_version:
    description: 'The version before update'
  commit_id:
    description: 'The id of the version update commit'
  subject:
    description: 'The version update commit subject'
  changelog:
    description: 'The changelog generated with all the commits in this release'

runs:
  using: 'node12'
  main: 'dist/index.js'

