name: 'bump-version-action'
description: 'Conventional commits compliant version manager.'
branding:
  icon: bookmark
  color: blue

inputs:
  version-tag-prefix:
    description: 'version tag prefix. Default: v'
    default: 'v'
    required: false
  release-user-name:
    description: 'the user name used for commit the release'
    required: true
  release-user-email:
    description: 'the user email used for commit the release'
    required: true
  release-subject:
    description: 'the release commit subject pattern'
    required: false
    default: 'release: {version} [skip ci]'
  release-body:
    description: 'the release content pattern'
    required: false
    default: '{changelog}'

outputs:
  version:
    description: 'the new package version'

runs:
  using: 'node12'
  main: 'dist/index.js'

