name: 'bump-version-action'
description: 'Conventional commits compliant version manager.'
icon: bookmark
color: blue

inputs:
  version-tag-prefix:
    description: 'version tag prefix. Default: v'
    default: 'v'
    required: false

outputs:
  version:
    description: 'the new package version'

runs:
  using: 'node12'
  main: 'dist/index.js'

