= bump-version-action
![publish](https://github.com/kbasepw/bump-version-action/workflows/publish/badge.svg)
![CodeQL](https://github.com/kbasepw/bump-version-action/workflows/CodeQL/badge.svg)

Conventional commits compliant version update action for GitHub Workflows.

This action will search the last version tag and bump package version based on
conventional commits rules.

== Rules

|===
| type | version level

| fix
| PATCH

| feat
| MINOR

| feature
| MINOR

| BREAKING CHANGE
| MAJOR

|===

Any other commit type (like docs, test, chore) will be ignored for version bump.

== Already tagged commits

If last commit has already a version tag then this action will finish and output
that version.

== Usage

=== Action inputs

|===
| Name | Description | Default value | Required

| commit-user-name
| The user name used to create the version update commit.
| <env:GITHUB_ACTOR>
| No

| commit-user-email
| The user email used to create the version update commit.
| <commit-user-name>@<repository owner/organization>
| No

| commit-message
| The message of the version update commit. (see message fields for reference).
| release: new release {version} [skip ci]\n\n{changelog}
| No

| commit-add
| Additional files to add to the version update commit.
|
| No

| version-tag-prefix
| The prefix used in version tag name.
| v
| No

|===

==== Message fields

this are the available fields for compose commit message:

|===
| Name | Description

| version 
| The calculated new version

| current_version
| The version before update.

| changelog
| The changelog generated with all the commits in this release.

|===

=== Action outputs

|===
| Name | Description

| version
| The calculated new version

| current_version
| The version before update.

| commit_id
| The id of the version update commit

| subject
| The version update commit subject

| changelog
| The changelog generated with all the commits in this release.

|===

=== Example

```yaml
name: publish workflow
on:
  push:
    branches:
      - $default-branch

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository (with all tags)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: bump version
        id: version-bump
        uses: kbasepw/bump-version-action
        with:
          version-tag-prefix: v
          commit-user-name: CI System
          commit-user-email: ci_admin@example.com
          commit-message: |
            release: new release {version} [skip ci]

            {changelog}

      - name: some other step
        run: echo ${{ steps.version-bump.outputs.version }}
```

