name: publish

on:
  push:
    branches: 
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm install && npm test

  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: prebuild action
      run: npm install && npm run build

    - id: bump-version
      name: bump package version
      uses: ./

    - name: output variable value
      run: echo ${{ steps.bump-version.outputs.version }}
