name: publish

on:
  push:
    branches: 
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build action
      run: npm install && npm run build

    - name: test
      run: npm test

    - id: bump-version
      name: bump package version
      uses: ./

    - name: action outputs
      run: ${{ toJson(steps.bump-version.outputs) }}
