name: publish

on:
  push:
    branches: 
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: create local branch
      run: git checkout -b ci --track ${GITHUB_REF:-origin/master}

    - name: build action
      run: npm install && npm run build

    - name: test
      run: npm test

    - id: bump-version
      name: bump package version
      uses: ./
      with:
        commit-add: dist/*

    - name: action outputs
      run: echo '${{ toJson(steps.bump-version.outputs) }}'

    - name: push
      run: git push --tags && git push --all

