name: publish

on:
  push:
    branches: 
      - $default-branch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm test

  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ./
      id: version-bump

    - name: output variable value
      run: echo ${{ steps.version-bump.version }}
